name: Docker

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:RestSMTP"
          platforms: linux/amd64, linux/arm64
          push: true
          tags: chrisrkw/restsmtp:latest
