name: Docker

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker --version
      - name: docker build
        run: |
          docker build --pull --no-cache -t chrisrkw/restsmtp:latest RestSMTP/
