name: Docker

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:RestSMTP"
          platforms: linux/386, linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64, linux/mips64le, linux/ppc64le, linux/s390x
          push: true
          tags: chrisrkw/restsmtp:latest

      # - name: build
      #   run: docker build --pull --no-cache -t chrisrkw/restsmtp:latest RestSMTP/
      # - name: push
      #   run: docker push chrisrkw/restsmtp:latest
